### ISSUE TITLE
Error on Three orbit control on both Windows and Linux OS

### ISSUE THREAD

**Issue by nanma56** [kitextech/kitesim#1]
To whom it may concern,

I was trying to download the code and do some experiments. After I typed "gulp", I saw the follow error messages. Please advise.

Thank you

TypeScript error: src/js/kite.ts(167,42): Error TS2345: Argument of type 'Matrix3' is not assignable to parameter of type 'Matrix4'.
  Property 'copyPosition' is missing in type 'Matrix3'.
TypeScript error: src/js/main.ts(9,39): Error TS7016: Could not find a declaration file for module 'three-orbit-controls'. '/users/nnanma/kitesim/node_modules/three-orbit-controls/index.js' implicitly has an 'any' type.
  Try `npm install @types/three-orbit-controls` if it exists or add a new declaration (.d.ts) file containing `declare module 'three-orbit-controls';`
TypeScript error: src/js/main.ts(19,8): Error TS1192: Module '"node_modules/@types/dat-gui/index"' has no default export.
TypeScript error: src/js/mcposition.ts(40,39): Error TS2339: Property 'clone' does not exist on type 'void'.
TypeScript error: src/js/pathfollow.ts(47,30): Error TS2339: Property 'LineLoop' does not exist on type 'typeof "node_modules/@types/three/index"'.
TypeScript error: src/js/pathfollow.ts(62,13): Error TS2322: Type 'void' is not assignable to type 'Vector3'.
[20:12:31] 3580917 bytes written (1.98 seconds)

**Comment by aokholm** [comment]
Thanks for the feedback.

Unfortunately there is some Typescript errors as you can see. 
I will try to see if I can get rid of them in a future update, but for now they shouldn't impact the output.

**Comment by nanma56** [comment]
Hi there,

Really thank you for the feedback. So far, the SIM is not really running because of this error on the gulp. The index.html is a black screen. Do I need to write an execution script to have it showing what you have Demoed?

Thank you for your advice.

Regards

Nan

**Comment by aokholm** [comment]
Hi Nan

Sorry for slow response. There is a lot of different tasks to take care of atm. The bug that seems to cause the simulator not to run was related to a node dependency dat-gui that didn't install correctly anymore.

The Typescripts error messages is unfortunately still to be expected.
